sudo: false
language: python
python:
 - "2.7"
 - "3.4"
env:
 - TOX_ENV=flake8
 - TOX_ENV=pydocstyle
 - TOX_ENV=py27
 - TOX_ENV=py3
install:
 - pip install codecov
 - pip install tox-travis
script:
 - tox -e $TOX_ENV
after_success:
 - codecov
